{% set name = "napari-input-visualizer" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 985df8f0dd5ad9e480aefea8f42aaee63b57e11724faf4cd44e3252ec5c65c3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - wheel
  run:
    - imageio-ffmpeg
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy

test:
  imports:
    - napari_input_visualizer
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bauerdavid/napari-input-visualizer
  summary: Visualize keyboard and mouse button presses
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bauerdavid
    - jaimergp
